name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build-test:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest, windows-latest ]
    name: 'Test, ${{ matrix.os }}, java ${{ matrix.java }}'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: ./.github/actions/setup_java
        with:
          java_version: ${{ matrix.java }}
      - name: Build
        uses: ./.github/actions/build
        with:
          java_version: ${{ matrix.java }}
      - name: Publish Eclipse update site
        if: runner.os == 'Linux' && github.repository == 'vlsi/mat-calcite-plugin' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/publish-update-site
        with:
          update_site_token:
            ${{ secrets.UPDATE_SITE_TOKEN }}
